version: '3.9'

services:
  mysql:
    build:
      context: ./mysql-init
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: car4me
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p12345678"]
      interval: 5s
      timeout: 3s
      retries: 10

  node:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: car4me

volumes:
  mysql_data:

